// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscRioCNuFZmvg3sApDdkeKBc6i2YgqNM',
    appId: '1:90378089259:web:17a0be026d2d4cd8b9cb6e',
    messagingSenderId: '90378089259',
    projectId: 'anime-ranking-ra',
    authDomain: 'anime-ranking-ra.firebaseapp.com',
    storageBucket: 'anime-ranking-ra.appspot.com',
    measurementId: 'G-5RE0QRNNRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtxKwVlI1QJlkwFE5ceXWGzhl6sCkFPM',
    appId: '1:90378089259:android:e5f644226e442b7fb9cb6e',
    messagingSenderId: '90378089259',
    projectId: 'anime-ranking-ra',
    storageBucket: 'anime-ranking-ra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBprM-6roJWsS5wKqoue9MnK_XIE8sE5JI',
    appId: '1:90378089259:ios:9fbc1faf000b04a0b9cb6e',
    messagingSenderId: '90378089259',
    projectId: 'anime-ranking-ra',
    storageBucket: 'anime-ranking-ra.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBprM-6roJWsS5wKqoue9MnK_XIE8sE5JI',
    appId: '1:90378089259:ios:9fbc1faf000b04a0b9cb6e',
    messagingSenderId: '90378089259',
    projectId: 'anime-ranking-ra',
    storageBucket: 'anime-ranking-ra.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBscRioCNuFZmvg3sApDdkeKBc6i2YgqNM',
    appId: '1:90378089259:web:2b67a9c3bfecbad3b9cb6e',
    messagingSenderId: '90378089259',
    projectId: 'anime-ranking-ra',
    authDomain: 'anime-ranking-ra.firebaseapp.com',
    storageBucket: 'anime-ranking-ra.appspot.com',
    measurementId: 'G-VRZ772C6V0',
  );
}
